name: CI/CD Pipeline

# Triggers
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
# environment variables
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository}}
  PYTHON_VERSION: "3.11"
  jobs:
  # Job 1: Linting and Code Quality
  lint:
    name: Code Linting & Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Run Black (code formatting)
        run: black --check --diff src/ tests/
      
      - name: Run isort (import sorting)
        run: isort --check-only --diff src/ tests/
      
      - name: Run flake8 (linting)
        run: flake8 src/ tests/
      
      - name: Run pylint (static analysis)
        run: pylint src/
      
      - name: Run mypy (type checking)
        run: mypy src/
